[tool.ruff]
line-length = 88
target-version = "py310"

# Enable specific lint rule groups
lint.select = ["E", "F", "W", "I"]  # E = style, F = flakes, W = warnings, I = isort
lint.ignore = ["E501"]  # Ignore long line rule if needed
lint.fixable = ["ALL"]

# Ignore typical non-source folders
exclude = ["migrations", "__pycache__", ".venv"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true

[tool.ruff.lint.isort]
force-single-line = true
