name: CI/CD Pipeline

# 👇 Trigger this workflow on pushes to main or dev branches
on:
  push:
    branches: [main, dev]

jobs:
  backend-ci:
    name: Run backend tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install backend requirements
        run: |
          pip install -r mygpt-backend/requirements.txt

      - name: Lint backend code with Ruff
        run: |
          cd mygpt-backend
          ruff check app/

      - name: Run backend tests (skipped for now)
        run: 'echo "TODO: Add backend tests"'

  frontend-ci:
    name: Lint & Check Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install frontend requirements
        run: |
          pip install -r mygpt-frontend/requirements.txt

      - name: Lint frontend with ruff
        run: |
          cd mygpt-frontend
          ruff check .
